# Generated by Django 4.1.5 on 2023-07-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='insta_link',
            new_name='Linkedin_link',
        ),
    ]
