# Generated by Django 4.2.3 on 2023-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_alter_youtuber_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='subs_count',
            field=models.CharField(max_length=255),
        ),
    ]
